// @ts-nocheck

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Channels
 * OpenAPI spec version: 1.0.0
 */
export interface BotCommand {
  command: string;
  description: string;
}

export interface SetMyCommandsRequest {
  commands: BotCommand[];
  language_code?: string;
}

export interface SetMyNameRequest {
  name?: string;
  language_code?: string;
}

export interface WebAppInfo {
  url: string;
}

export interface MenuButtonWebApp {
  type: string;
  text: string;
  web_app: WebAppInfo;
}

export interface SetChatMenuButtonRequest {
  menu_button: MenuButtonWebApp;
}

export interface ChannelItem {
  id: number;
  title: string;
  userName?: string;
  /** @nullable */
  photo: string | null;
}

export interface GetChannelsResponse {
  total: number;
  data: ChannelItem[];
}

export interface GetChannelResponse {
  /** @nullable */
  title: string | null;
  username: string;
  about: string;
  /** @nullable */
  photo: string | null;
  isSubscribed: boolean;
  recommendations: ChannelItem[];
}

export interface Subscription {
  id: string;
  /** @nullable */
  createdAt: string | null;
  /** @nullable */
  userId: string | null;
  /** @nullable */
  channelId: string | null;
}

export interface GetSearchChannelsResponse {
  total: number;
  data: ChannelItem[];
}

export type GetChannelsParams = {
  take?: number;
  skip?: number;
};

export type ChannelsSearchParams = {
  take?: number;
  skip?: number;
  query: string;
};
