// @ts-nocheck

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Channels
 * OpenAPI spec version: 1.0.0
 */
export interface ChannelItem {
  id: string;
  title: string;
  userName?: string;
  /** @nullable */
  photo: string | null;
}

export interface GetChannelsResponse {
  total: number;
  data: ChannelItem[];
}

export interface GetSearchChannelsResponse {
  total: number;
  data: ChannelItem[];
}

export type GetChannelsParams = {
  take?: number;
  skip?: number;
};

export type ChannelsSearchParams = {
  take?: number;
  skip?: number;
  query: string;
};
