// @ts-nocheck

/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Channels
 * OpenAPI spec version: 1.0.0
 */
export interface SearchChannelsItem {
  id: string;
  title: string;
  userName?: string;
  /** @nullable */
  photo: string | null;
}

export interface GetSearchChannelsResponse {
  total: number;
  data: SearchChannelsItem[];
}

export type GetSearchChannelsParams = {
  take?: number;
  skip?: number;
  query: string;
};
